#     _            _
#  __| |_ _  _ _ _| |____ _
# / _| ' \ || | '_| / / _` |
# \__|_||_\_,_|_| |_\_\__,_|
#
# made by 4urqa

# Font #
font_family Geist Nerd Font Mono
font_size 15

# Cursor #
cursor_shape underline
cursor_shape_unfocused underline
cursor_blink_interval 0
cursor_trail 1

# Window #
scrollback_lines 5000
window_margin_width 0 8
confirm_os_window_close 0
background_opacity 0.9

# Theme #
background  #0f0f0f
foreground  #f0f0f0

cursor                #f0f0f0
selection_foreground  #f0f0f0
selection_background  #4f4f4f

color0  #2f2f2f
color8  #4f4f4f

# red
color1                #d9534f
# light red
color9                #d9534f

# green
color2               #7BA05B
# light green
color10               #7BA05B

# yellow
color3                #f1c15c
# light yellow
color11               #f1c15c

# blue
color4                #54a8e3
# light blue
color12               #54a8e3

# magenta
color5                #d852a3
# light magenta
color13               #d852a3

# cyan
color6                #5bc0de
# light cyan
color14               #5bc0de

# light gray
color7                #8f8f8f
# dark gray
color15               #4f4f4f
