-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--         _         _                       _

-- __ __ _(_)_ _  __| |_____ __ __  _ _ _  _| |___ ___

-- \ V  V / | ' \/ _` / _ \ V  V / | '_| || | / -_|_-<

--  \_/\_/|_|_||_\__,_\___/\_/\_/  |_|  \_,_|_\___/__/

--#WINDOW RULES

--#LAYER RULES
