"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
"""

right_format = ""

[os]
disabled = false
format = '[$symbol ]($style)'
style = 'bold blue'

[username]
show_always = true
style_user = "fg:#f0f0f0"
format = '[$user]($style)'

[directory]
style = "fg:#f0f0f0"
format = "[ $path ]($style)"

[custom.giturl]
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""

[git_branch]
format = '  on [$branch]($style)(#0f0f0f)'

[git_status]
style = "bold yellow"
format = '([\[$all_status$ahead_behind\]]($style) )'
